import { PageContent } from './types';

export const enContent: PageContent = {
  landing: {
    heroDesc: 'Reliable, step-by-step guidance in your mother tongue for cooperative by-laws, government schemes, crop insurance (PMFBY), PACS services, financial literacy, and grievance redressal.',
    stepsBadge: 'Accessible Rural Design',
    stepsTitle: 'Break Language Barriers, Access Direct Services',
    stepsSubtitle: 'Empowerment in 4 simple guided steps',
    fourSteps: [
      { step: '1. Speak', desc: 'Ask your question in your mother tongue using voice or text.' },
      { step: '2. Understand', desc: 'AI accurately grasps your local cooperative or farming query.' },
      { step: '3. Guide', desc: 'Receive structured checklist, documents required, and authorized offices.' },
      { step: '4. Act', desc: 'File your PMFBY claim within 72 hours or submit a tracked grievance.' },
    ],
    coreCaps: [
      {
        title: 'Cooperative Governance & By-laws',
        desc: 'Understand membership rights, AGM resolutions, dividend rules, and election procedures.',
        link: 'View Governance',
      },
      {
        title: 'PMFBY Crop Insurance & Claims',
        desc: 'How to notify localized crop damage within 72 hours? Required documents and claim tracking.',
        link: 'View 72-Hour Rule',
      },
      {
        title: 'PACS Services & Rural Kiosks',
        desc: 'Low-interest crop loans (KCC), fertilizer distribution, custom hiring centers, and CSC services.',
        link: 'Explore PACS',
      },
    ],
    targetBadge: 'Target Stakeholders',
    targetTitle: 'A Trusted Digital Companion for Farmers & Rural Communities',
    targetSubtitle: '',
    stakeholders: ['Farmers & Tenant Cultivators', 'Cooperative Members', 'PACS Society Members', 'Cooperative Staff', 'Women Self-Help Groups (SHGs)', 'Rural Agri-Entrepreneurs'],
  },
  dashboard: {
    farmerGreeting: (name) => `Farmer Mr. ${name}, select any category below to access cooperative guidance, crop insurance, or rural banking services.`,
    suggestedTitle: 'Frequently Asked Questions (Suggested Inquiries):',
    pillarsTitle: 'Key Service Pillars',
    pillarsCount: '8 Core Pillars',
    serviceCards: [
      { id: 'cooperative', title: '🤝 Cooperative Help', desc: 'Society registration, member statutory rights, dividends, and AGM guidelines.', badge: 'Cooperatives', color: 'hover:border-emerald-500' },
      { id: 'pmfby', title: '🌾 Crop Insurance (PMFBY)', desc: 'Calamity damage claims, mandatory 72-hour reporting rule, and required documents.', badge: '72-Hour Rule', color: 'hover:border-amber-500' },
      { id: 'schemes', title: '🏛 Government Schemes', desc: 'Ministry of Cooperation flagship schemes, grain storage, and PACS digitization.', badge: 'Schemes', color: 'hover:border-blue-500' },
      { id: 'pacs', title: '🏦 PACS Services', desc: 'Short-term KCC crop loans, subsidized fertilizer/seed distribution, and CSC services.', badge: 'Rural Banking', color: 'hover:border-indigo-500' },
      { id: 'financial', title: '💰 Financial Literacy', desc: 'EMI loan calculator, 3% interest subvention, secure UPI, and cyber safety.', badge: 'Calculator', color: 'hover:border-green-500' },
      { id: 'grievance', title: '📢 Grievance Support', desc: 'Guided grievance draft and official tracking ID for issues against PACS or societies.', badge: 'Support', color: 'hover:border-red-500' },
      { id: 'cooperative', title: '⚖ Legal & By-laws', desc: 'State cooperative society acts, model by-laws, and dispute resolution.', badge: 'Rules', color: 'hover:border-purple-500' },
      { id: 'voice', title: '🎙 Voice Assistant', desc: 'Speak in your regional language without typing and listen to spoken answers.', badge: '8 Languages', color: 'hover:border-orange-500' },
    ],
  },
  pacs: {
    badge: 'Primary Agricultural Credit Societies',
    title: 'PACS Services & Rural Empowerment',
    desc: 'Primary Agricultural Credit Societies (PACS) form the grassroots backbone of Indian agriculture, providing credit, quality agri-inputs, and citizen services at village doorsteps.',
    noteTitle: 'Service Availability Note:',
    noteDesc: 'Crop loans and fertilizer distribution are universally available across all PACS; specialized services like Common Service Centers (CSC), Custom Hiring Machinery, and Warehousing depend on the society adopting the Model By-laws.',
    coreTitle: '1. Core Essential Services',
    coreServices: [
      { title: 'Short-Term Crop Loan (KCC)', desc: 'Concessional crop loans at 7% p.a.; timely repayment unlocks a 3% government interest subvention, reducing effective interest to 0–4%.', tag: 'Credit' },
      { title: 'Fertilizer & Certified Seed Supply', desc: 'Reliable, subsidized distribution of Urea, DAP, complex fertilizers, and certified seeds directly in the village.', tag: 'Agri Inputs' },
      { title: 'MSP Procurement Centers', desc: 'Direct farmer registration and procurement of paddy, wheat, cotton, and pulses at Minimum Support Price (MSP).', tag: 'Procurement' },
    ],
    expandedTitle: '2. Modern Multi-Purpose Services',
    expandedServices: [
      { title: 'Common Service Center (CSC)', desc: 'Aadhaar updates, PM-KISAN e-KYC, digital land records (RoR/7/12) download, and utility bill payments right at the society.' },
      { title: 'Custom Hiring Machinery Centers', desc: 'Affordable rental of tractors, rotavators, seeders, and combine harvesters for small and marginal farmers.' },
      { title: 'Grain Storage & Electronic Warehouse Pledges', desc: 'Secure local storage allowing farmers to avoid distress sales and obtain immediate loans against e-NWR warehouse receipts.' },
    ],
    ctaTitle: 'Have Questions About Your Local PACS?',
    ctaDesc: 'Ask Sahakar Sathi about loan eligibility, fertilizer allotments, or filing an inquiry.',
    ctaBtn: 'Ask About PACS',
  },
  pmfby: {
    badge: 'Pradhan Mantri Fasal Bima Yojana Guide',
    title: 'Crop Insurance & Damage Compensation Process',
    desc: 'The flagship national crop insurance scheme providing comprehensive financial risk mitigation against natural calamities, unseasonal rain, hailstorms, and drought.',
    alertBadge: 'Mandatory Rule',
    alertTitle: 'Mandatory 72-Hour Reporting Window for Localized Calamities!',
    alertDesc: 'In case of localized post-harvest damage, hailstorm, or inundation, farmers must report the loss within 72 hours via the 14447 helpline or the Crop Insurance App.',
    alertBtn: 'Ask 72-Hour Rule',
    stepsTitle: '4 Steps to Claim Compensation',
    steps: [
      { step: 'Step 1: Intimate within 72 Hours', desc: 'Call toll-free 14447 or log an incident on the Crop Insurance Mobile App.' },
      { step: 'Step 2: Joint Field Survey', desc: 'A joint inspection is conducted by the revenue/agriculture officer and the insurance loss assessor.' },
      { step: 'Step 3: Loss Assessment Upload', desc: 'The survey report and geo-tagged damage photos are uploaded to the national portal.' },
      { step: 'Step 4: Direct Benefit Transfer (DBT)', desc: 'Approved claims are credited directly into the farmer’s Aadhaar-seeded bank account.' },
    ],
    docsTitle: 'Claim Checklist & Required Documents',
    docs: ['Aadhaar Card Copy', 'Land RoR / 7/12 & 8-A Extract', 'Crop Insurance Premium Receipt or Policy Number', 'Bank Passbook Copy (with clear IFSC)', 'Geo-tagged photograph of damaged crop'],
    faqTitle: 'Frequently Asked Questions (PMFBY FAQs)',
    faqs: [
      { q: 'Will my claim be accepted if reported after 72 hours?', a: 'No, localized calamity claims reported after 72 hours are rejected under national operational guidelines. Timely reporting is legally mandatory.' },
      { q: 'How much premium does the farmer pay?', a: 'Only 2% for Kharif food and oilseed crops, 1.5% for Rabi crops, and 5% for annual commercial/horticultural crops; the rest is subsidized by the government.' },
      { q: 'What if the insurance company delays the survey?', a: 'You can submit a grievance to the District Grievance Redressal Committee (DGRC) headed by the District Collector or file a ticket in Sahakar Sathi.' },
    ],
  },
  cooperative: {
    badge: 'Legal & Governance Guidance',
    title: 'Cooperative Governance, Rights & By-laws',
    desc: "Cooperative societies operate on the democratic pillar of 'One Member, One Vote'. Explore membership rights, Annual General Meetings (AGM), audits, and election regulations.",
    pillars: [
      {
        tag: 'Rule 1: Membership',
        title: 'Membership Eligibility & Statutory Rights',
        items: ['Any resident cultivator within the area of operation has the right to apply.', 'Equal right to access society loans, inputs, and fair voting rights.', 'Statutory right to inspect balance sheets, audit reports, and receive eligible dividends.'],
      },
      {
        tag: 'Rule 2: AGM',
        title: 'Annual General Meeting (AGM) Mandates',
        items: ['Mandatory to hold the AGM every year before September 30.', 'Approval of the audited accounts, dividend declaration, and annual budget.', 'Mandatory minimum 14 days prior notice with agenda to all members.'],
      },
      {
        tag: 'Rule 3: Transparency',
        title: 'Statutory Audit & Financial Transparency',
        items: ['Compulsory annual audit by government-empanelled certified auditors.', 'Audit classifications (A, B, C, D) reflect financial stability and governance health.', 'Members can petition the Registrar for a special inspection if fraud is suspected.'],
      },
      {
        tag: 'Rule 4: Elections',
        title: 'Board of Directors Elections & Disputes',
        items: ['Democratic elections every 5 years overseen by the State Cooperative Election Authority.', 'Mandatory statutory reservation for women and backward categories on the board.', 'Disputes can be escalated to the Assistant Registrar of Cooperative Societies (ARCS).'],
      },
    ],
    rightsTitle: 'Key Statutory Member Rights',
    rights: ['Fundamental Right to Vote', 'Right to Receive Declared Dividends', 'Right to Inspect Accounts & By-laws', 'Right to Requisition Special General Meetings', 'Right to Legal Redressal before the Cooperative Court'],
  },
  schemes: {
    badge: 'Flagship Schemes & Subsidies',
    title: 'Government Schemes & Subsidies for Cooperatives',
    desc: 'Verified, up-to-date guidance on flagship welfare initiatives by the Ministry of Cooperation and the Ministry of Agriculture.',
    whoItHelpsLabel: 'Target Beneficiaries:',
    benefitsLabel: 'Key Scheme Benefits:',
    applyLabel: 'How to Apply & Access:',
    askAiBtn: 'Ask AI About This Scheme',
    schemesList: [
      {
        id: 'pacs-comp',
        title: 'National PACS Computerization Project',
        whoItHelps: '63,000+ Primary Agricultural Credit Societies and over 130 million farmer members nationwide.',
        benefits: 'Transition from manual record-keeping to a unified cloud ERP, transparent loan sanctioning, and direct CSC digital delivery.',
        howToApply: 'Implemented through the State Cooperation Department in coordination with NABARD.',
        ministry: 'Ministry of Cooperation, Govt. of India',
        badge: '100% Centrally Funded',
      },
      {
        id: 'grain-storage',
        title: "World's Largest Decentralized Grain Storage Plan",
        whoItHelps: 'Farmers, PACS societies, and Farmer Producer Organizations (FPOs).',
        benefits: 'Construction of modern decentralized godowns, reducing post-harvest losses and enabling prompt loans against e-NWR receipts.',
        howToApply: 'Eligible PACS submit proposals via their District Central Cooperative Bank and NABARD DDM.',
        ministry: 'Ministry of Cooperation & NABARD',
        badge: 'Agri-Infrastructure Plan',
      },
      {
        id: 'ncel-export',
        title: 'National Cooperative Exports Limited (NCEL)',
        whoItHelps: 'Farmers, agri-enterprises, and primary producer cooperatives.',
        benefits: 'Direct international export channel for non-basmati rice, sugar, onion, and spices, returning global market profits to farmers.',
        howToApply: 'Cooperatives apply for institutional membership through the official NCEL portal.',
        ministry: 'Ministry of Cooperation & Ministry of Commerce',
        badge: 'Global Trade Gateway',
      },
      {
        id: 'pm-kisan',
        title: 'PM-KISAN Samman Nidhi Scheme',
        whoItHelps: 'All landholding farmer families across India.',
        benefits: 'Direct income support of ₹6,000 per year delivered in three equal four-monthly installments of ₹2,000 via DBT.',
        howToApply: 'Register at pmkisan.gov.in or visit your local village PACS CSC center for biometric e-KYC.',
        ministry: 'Ministry of Agriculture & Farmers Welfare',
        badge: '₹6,000 Direct Benefit',
      },
    ],
  },
  financial: {
    badge: 'Rural Financial Literacy',
    title: 'Financial Literacy, Secure Banking & Debt Management',
    desc: 'Understand loans, interest subvention, savings, and essential cyber safety guidelines for digital UPI transactions.',
    goldenRulesBadge: 'Cyber Safety & Fraud Prevention',
    goldenRulesTitle: '3 Golden Rules for Safe Digital Banking & UPI',
    goldenRules: [
      { title: 'Rule 1: You Never Need a PIN to Receive Money!', desc: 'Always remember: entering a UPI PIN debits money from your account. You NEVER enter a PIN to receive payments, refunds, or subsidies.' },
      { title: 'Rule 2: Bank Officials Never Ask for OTPs Over the Phone', desc: 'Never share OTPs, card CVVs, or passwords with anyone claiming to be a bank manager, cooperative secretary, or insurance surveyor.' },
      { title: 'Rule 3: In Case of Fraud, Call 1930 within 1 Hour', desc: 'If money is fraudulently deducted, immediately call the National Cyber Crime Helpline 1930 within the golden hour to freeze fund transfers.' },
    ],
    kccTitle: 'Kisan Credit Card (KCC) 3% Interest Subvention Math',
    kccDesc: 'How prompt repayment benefits the farmer:',
    kccPoints: ['Standard agricultural crop loan interest rate: 7% p.a.', 'Central Government prompt repayment discount: 3% Interest Subvention', 'Net interest rate paid by the farmer: only 4% p.a. (effectively 0% in several states with state subsidies)', 'Timely repayment unlocks a 10% credit limit enhancement each successive year'],
  },
  loanCalculator: {
    title: 'Understand My Loan Calculator',
    subtitle: 'Simplified EMI & interest estimation tool for rural farmers & cooperative members',
    badge: 'KCC Subvention Calculator',
    amountLabel: 'Loan Amount (₹):',
    rateLabel: 'Annual Interest Rate (%):',
    tenureLabel: 'Repayment Tenure (Months):',
    monthlyEmi: 'Estimated Monthly Installment (EMI)',
    totalInterest: 'Total Interest Payable',
    totalRepayment: 'Total Amount Repayable',
    kccDiscountTitle: 'Prompt Repayment Benefit (KCC 3% Subvention):',
    kccDiscountDesc: (saved) => `By repaying your loan on time, the Government 3% interest subvention saves you ₹${saved.toLocaleString('en-IN')}!`,
    disclaimer: '* This calculator is for educational guidance only. Actual installments depend on bank norms and specific state interest subsidy rules.',
  },
  grievance: {
    badge: 'Guided Citizen Redressal System',
    title: 'Grievance Filing & Escalation Support',
    desc: 'Draft an official complaint in 5 simple guided steps to submit to the appropriate cooperative registrar or insurance grievance authority.',
    categories: [
      { id: 'Cooperative Society', label: 'Cooperative Society', desc: 'Meetings, AGM audit, elections, or membership disputes' },
      { id: 'PACS', label: 'PACS / Village Society', desc: 'Crop loan refusal, fertilizer distribution, or irregularities' },
      { id: 'Crop Insurance (PMFBY)', label: 'Crop Insurance (PMFBY)', desc: 'Survey not conducted within 72 hrs, claim delay or wrongful rejection' },
      { id: 'Government Scheme', label: 'Government Scheme', desc: 'PM-KISAN installment issue, e-KYC roadblock, or subsidy delay' },
      { id: 'Banking / Financial', label: 'Banking & Financial', desc: 'Interest subvention not credited, unauthorized deduction, or ATM failure' },
      { id: 'Other', label: 'Other Inquiries', desc: 'General rural agriculture or cooperative concerns' },
    ],
    step1Title: 'Step 1: Select Grievance Category',
    step1Desc: 'Choose the subject matter that best matches your issue:',
    step2Title: 'Step 2: Describe Your Issue',
    step2Desc: 'State what happened in simple words (society name, date, what went wrong):',
    step2Placeholder: 'e.g. My soybean crop was destroyed by unseasonal rain. I reported within 72 hours, but no joint survey has been conducted yet...',
    step3Title: 'Step 3: Complainant Details & Supporting Documents',
    step3Desc: 'Provide contact information and optional supporting documentation:',
    nameLabel: 'Full Name:',
    districtLabel: 'District & State:',
    uploadDocLabel: 'Attach Proof / Document (Optional):',
    step4Title: 'Step 4: Summary & Verification',
    step4Desc: 'Review the structured draft prepared by Sahakar Sathi:',
    complainantLabel: 'Complainant:',
    categoryLabel: 'Category:',
    jurisdictionLabel: 'Competent Authority:',
    confirmSubmitBtn: 'Submit Official Grievance',
    step5Success: 'Grievance Successfully Recorded!',
    trackingIdLabel: 'Grievance Tracking ID:',
    statusLabel: 'Current Status:',
    assignedAuthLabel: 'Assigned Department / Officer:',
    trackRecordNotice: 'Save this Tracking ID. You can check the resolution status at any time.',
    nextBtn: 'Next Step',
    backBtn: 'Back',
    newGrievanceBtn: 'File Another Grievance',
    trackTitle: 'Track Grievance Status',
    trackSubtitle: 'Enter your tracking ID to monitor ongoing review and official notes',
    trackPlaceholder: 'e.g. SAH-2026-001245',
    trackBtn: 'Check Status',
  },
  contacts: {
    badge: 'Official Directory & Helplines',
    title: 'Government Helplines & Emergency Contacts',
    desc: 'Verified, toll-free helpline numbers for crop insurance, cyber fraud, consumer protection, and cooperative registries.',
    contactsList: [
      {
        title: 'National Crop Insurance Helpline (PMFBY)',
        number: '14447',
        desc: 'Report crop damage within 72 hours, check claim status, and register surveyor complaints.',
        timing: '24/7 Available (Toll-Free)',
        category: 'Crop Insurance',
        color: 'bg-amber-500',
      },
      {
        title: 'Kisan Call Center (KCC Agri Advisory)',
        number: '1551',
        desc: 'Direct agricultural expert advice on farming techniques, weather forecasts, pest alerts, and subsidies.',
        timing: '6:00 AM to 10:00 PM (Toll-Free)',
        category: 'Agri Advisory',
        color: 'bg-[#0B6B4F]',
      },
      {
        title: 'National Cyber Crime Helpline',
        number: '1930',
        desc: 'Call immediately within the golden hour if you fall victim to financial fraud, OTP theft, or UPI scams.',
        timing: '24/7 Available (Immediate)',
        category: 'Cyber Safety',
        color: 'bg-red-600',
      },
      {
        title: 'National Consumer Helpline (NCH)',
        number: '1915',
        desc: 'File consumer disputes regarding defective fertilizers, seeds, or substandard commercial services.',
        timing: '9:30 AM to 5:30 PM',
        category: 'Consumer Rights',
        color: 'bg-blue-600',
      },
      {
        title: 'Cooperative Commissioner Grievance Cell',
        number: '1800-233-0244',
        desc: 'Escalate governance disputes, embezzlement, or misconduct in cooperative credit societies.',
        timing: 'Working Days (10:00 AM - 5:00 PM)',
        category: 'Cooperation Dept',
        color: 'bg-teal-600',
      },
      {
        title: 'District Central Cooperative Bank (DCCB)',
        number: '0253-2575501',
        desc: 'Inquire about PACS crop loan disbursement, KCC issuance, and direct subsidy credit.',
        timing: '10:00 AM to 5:00 PM',
        category: 'District Bank',
        color: 'bg-indigo-600',
      },
    ],
  },
  kiosk: {
    badge: 'Rural Self-Service Architecture',
    title: 'Rural Cooperative AI Kiosk Architecture',
    desc: 'A ruggedized, voice-first standalone kiosk designed for installation in village PACS offices, Gram Panchayats, and APMC market yards.',
    note: 'Kiosk Blueprint: This hardware model represents the deployment architecture for physical touchpoints in rural PACS and APMC centers.',
    terminalTitle: 'Sahakar Sathi Autonomous Edge Terminal',
    terminalDesc: 'Dust-resistant (IP65 Rugged), solar-powered, and operated via simple one-tap voice interactions.',
    specs: [
      { title: '21.5" Sunlight-Readable Touchscreen', desc: '1000-nit high-brightness Gorilla Glass display visible even under direct sunlight with large, elder-friendly touch buttons.' },
      { title: 'Noise-Cancelling Array Microphone & Speaker', desc: 'Dual-mic beamforming audio capture designed to filter out ambient APMC mandi noise and deliver loud, clear voice answers.' },
      { title: 'Biometric Aadhaar & Fingerprint Scanner', desc: 'Instant farmer verification for PM-KISAN e-KYC, PACS member authentication, and verified citizen requests.' },
      { title: 'Thermal Receipt & Guidance Printer', desc: 'Instant paper printouts of grievance tracking slips, PMFBY claim steps, and loan repayment calculation sheets.' },
      { title: 'Hybrid Solar Backup (Solar & 4G/5G)', desc: 'Designed for rural power conditions with 8-hour built-in solar battery backup and dual-SIM automatic network failover.' },
      { title: 'Offline Edge Knowledge Cache', desc: 'Essential cooperative regulations, 72-hour rules, and emergency contacts remain operational even during internet dropouts.' },
    ],
  },
  impact: {
    badge: 'Strategic DPI Architecture',
    title: 'Sahakar Sathi — National Impact, Architecture & Roadmap',
    desc: '10 transformative impacts empowering farmers and cooperative members under the vision of the Ministry of Cooperation and NCCT.',
    impactTitle: '10 Transformative Impacts of Sahakar Sathi',
    impacts: [
      { num: '1', title: 'Zero Language Barrier', desc: 'Bilingual voice and text across 8 Indian languages with synchronized audio response.' },
      { num: '2', title: 'Cooperative Governance Literacy', desc: 'Demystifying statutory rights, AGM procedures, dividends, and election rules for ordinary members.' },
      { num: '3', title: 'Demystifying Government Schemes', desc: 'Direct eligibility and application pathways for PACS Computerization, grain storage, and NCEL exports.' },
      { num: '4', title: 'PMFBY 72-Hour Safeguard', desc: 'Protecting farmers against claim rejection due to delayed intimations with clear guidance.' },
      { num: '5', title: 'Rural Financial Literacy', desc: 'Practical loan EMI calculations and widespread education on the rule that "Receiving money requires no PIN".' },
      { num: '6', title: 'Guided Grievance Redressal', desc: 'Transforming confusion into actionable 5-step complaint drafts with official tracking identifiers.' },
      { num: '7', title: 'Voice-First Rural Accessibility', desc: 'Complete voice interface catering to varying literacy levels without requiring complex typing.' },
      { num: '8', title: 'Rural Kiosk & Hardware Ready', desc: 'Full hardware blueprint ready for deployment across 63,000+ PACS and agricultural market yards.' },
      { num: '9', title: 'Verified Grounded Knowledge', desc: 'Official gazette and guideline-grounded answers eliminating hallucination in critical legal matters.' },
      { num: '10', title: 'Nationally Scalable Infrastructure', desc: 'Fully aligned with the Ministry of Cooperation and NCCT objectives, ready to scale across all Indian states.' },
    ],
    archBadge: 'Technical Architecture',
    archTitle: 'Retrieval-Augmented Generation (RAG) Architecture',
    archDesc: 'Enterprise-grade, cloud-ready architecture built for high availability and strict data governance:',
    layers: [
      { title: '1. Client Presentation Layer', desc: 'React + TypeScript + Vite + Tailwind CSS. 8-language localization with Web Speech API integration.', color: 'text-[#0B6B4F]' },
      { title: '2. Secure Application Server', desc: 'Node.js + Express backend proxy preventing API key exposure to browser clients.', color: 'text-blue-700' },
      { title: '3. Grounded Knowledge Engine', desc: 'Structured legal, cooperative, and insurance knowledge repositories with metadata verification.', color: 'text-amber-700' },
      { title: '4. Google Gemini AI & Guardrails', desc: 'Gemini 3.8 Flash model with strict regulatory system instructions and statutory disclaimers.', color: 'text-emerald-800' },
    ],
    scenariosTitle: 'Interactive Workflow Scenarios',
    scenariosSubtitle: 'Click any scenario below to test end-to-end execution:',
    scenarios: [
      { tag: 'Scenario 1 (Marathi):', title: '"मला पीक विम्याबद्दल माहिती हवी आहे"' },
      { tag: 'Scenario 2 (Hindi):', title: '"PACS से किसानों को क्या लाभ मिलता है?"' },
      { tag: 'Scenario 3 (Grievance):', title: '5-step grievance filing with tracking ID generation' },
      { tag: 'Scenario 4 (Loan Tool):', title: '₹1,00,000 crop loan EMI with 3% interest subvention' },
      { tag: 'Scenario 5 (Voice Assistant):', title: 'Voice input and automated spoken guidance' },
      { tag: 'Scenario 6 (Hardware Kiosk):', title: 'Touchscreen kiosk blueprint for village PACS' },
    ],
  },
  voiceAssistant: {
    badge: 'Rural Voice Assistant',
    title: 'Voice Assistant',
    desc: 'Speak in your regional language without typing and listen to spoken answers.',
    troubleshootBtn: 'Voice not working? Click here for quick fixes',
    speakerTestBtn: 'Test Speaker',
    troubleshootTitle: 'Steps to enable and troubleshoot voice features:',
    step1Title: '1. Allow Microphone Permission',
    step1Desc: 'Click the 🔒 lock or site settings icon on the left of your browser address bar. Set "Microphone" to Allow, then reload.',
    step2Title: '2. Recommended Browser',
    step2Desc: 'For optimal Web Speech API speech recognition, use Google Chrome or Microsoft Edge.',
    step3Title: '3. Check Speaker & Volume',
    step3Desc: 'Ensure your phone/laptop audio is unmuted. Click the "Test Speaker" button above to verify audio playback.',
    micErrorTitle: 'Microphone or Audio Notice:',
    retryBtn: 'Retry Permission',
    closeBtn: 'Close',
    heroBadge: 'Voice-First Rural Assistance',
    heroSubtitle: 'Sahakar Sathi listens to your spoken query, prepares clear guidance, and speaks it aloud in your language.',
    statusTapToSpeak: 'Tap the microphone and speak (Tap to Speak)',
    statusListening: 'Listening... please speak clearly',
    liveTranscriptionTitle: 'Capturing speech in real time (Live Transcription):',
    queryLabel: 'Your Query:',
    thinkingLabel: 'Sahakar Sathi is formulating your answer and preparing audio...',
    manualPlaceholder: 'Or type your question here...',
    askBtn: 'Ask',
    instantVoiceTitle: 'Tap any question below to test audio playback without speaking:',
    instantVoiceSubtitle: 'Instant Audio Response',
    listenLabel: 'Listen',
    voiceResponseTitle: 'Voice Assistant Response:',
    replayLabel: 'Replay Audio',
  },
  chat: {
    activeStatus: 'Active',
    subTitle: 'Multilingual Cooperative & Agricultural Companion',
    voiceBtn: 'Voice Assistant',
    sectionLabel: 'Category:',
    chips: [
      { label: '🌾 Crop Insurance (PMFBY)', category: 'Crop Insurance' },
      { label: '🏦 PACS Services', category: 'PACS Services' },
      { label: '🤝 Cooperative Governance', category: 'Cooperative Governance' },
      { label: '🏛 Government Schemes', category: 'Government Schemes' },
      { label: '💰 Financial Literacy', category: 'Financial Literacy' },
      { label: '📢 File Grievance', category: 'Grievance Redressal' },
    ],
    thinking: 'Sahakar Sathi is formulating structured advice...',
    suggestedLabel: 'Suggested Questions:',
    inputPlaceholder: 'Ask about cooperatives, crop insurance, PACS or schemes...',
    listeningPlaceholder: 'Listening... please speak clearly...',
  },
  history: {
    badge: 'Citizen Portal Records',
    title: 'My Queries & Grievance History',
    desc: 'Review your past questions, Sahakar Sathi answers, and recorded grievances.',
    activeMemberBadge: 'Active Member',
    villageLabel: 'Village:',
    districtLabel: 'District:',
    pacsLabel: 'PACS Member ID:',
    allTab: 'All History',
    queriesTab: 'My Inquiries',
    grievancesTab: 'Filed Grievances',
    noHistory: 'No history recorded yet. Ask a question or file a grievance to begin!',
    demoNotice: 'Session Storage: Your inquiries and tracking numbers are securely kept in this session.',
  },
  admin: {
    badge: 'Knowledge & Guidance Base',
    title: 'Official Knowledge Base',
    desc: 'Official repository of cooperative acts, government gazettes, PMFBY guidelines, and verified citizen advisories.',
    searchPlaceholder: 'Search verified knowledge base...',
    allCategories: 'All Categories',
    verifiedBase: 'Verified Knowledge Base',
    totalArticles: 'Total Official Articles',
  },
  aiResponse: {
    officialAssistant: 'Official Assistant',
    requirement: 'Eligibility / Requirement',
    actionSteps: 'Action Steps',
    documents: 'Required Documents',
    whereToGo: 'Where to Go / Authorized Office:',
    importantNote: 'Important Notice:',
  },
};
